dependencies {
  // openflexo dep
  implementation flexoFoundation()
  implementation flexoUi()
  implementation fmlTechnologyAdapterUi()
  implementation fmlRtTechnologyAdapterUi()
  implementation diagramConnector()
  implementation diagramConnectorUi()
  implementation ginaConnector()
  implementation ginaConnectorUi()
  implementation fmlDiagrammingExtension()
  implementation fmlGinaExtension()
  // external dep

  // testing dep
  testImplementation flexoFoundationTest()
  testImplementation flexoUiTest()
}
